table 'Countries with Flags URL'
	lineageTag: a6e27a3f-b852-415e-81f1-6e713ec7b779

	column Country
		dataType: string
		lineageTag: 79beb94b-7eac-4b19-93dd-370de16d3eea
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Country code'
		dataType: string
		lineageTag: 2802ffae-59dc-4ecf-8e03-810a21538560
		summarizeBy: none
		sourceColumn: Country code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4c085877-d17b-4308-9291-ea60d9e73c14
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Flag
		dataType: string
		lineageTag: f4282c49-ce88-4946-92f3-cabac574e675
		summarizeBy: none
		sourceColumn: Flag

		annotation SummarizationSetBy = Automatic

	partition 'Countries with Flags URL' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Projects\Power BI\Project-2\Dataset's\BMW Files\Countries with Flags URL.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"Country code", type text}, {"Region", type text}, {"Flag", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

