table 'Model Table'
	lineageTag: a9869dc4-eadd-4723-b33a-242100c5cda9

	column 'Model ID'
		dataType: int64
		formatString: 0
		lineageTag: 8cdd7555-c404-48f8-bfc4-656e90e5abb1
		summarizeBy: none
		sourceColumn: Model ID

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: c672aa10-9d7c-475d-9383-878b801ef705
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Image
		dataType: string
		lineageTag: 87680ef5-f959-439b-b9b5-f2b5c90bacfe
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	partition 'Model Table' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Projects\Power BI\Project-2\Dataset's\BMW Files\BMW_Sales_Data.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type text}, {"Year", Int64.Type}, {"Model", type text}, {"Revenue", Int64.Type}, {"Quantity Sold", Int64.Type}, {"Region", type text}, {"Country", type text}, {"Channel", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Date] <> null and [Date] <> ""),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Model"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Model"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Model ID"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Model"}, #"Car Images", {"Model"}, "Car Images", JoinKind.LeftOuter),
				    #"Expanded Car Images" = Table.ExpandTableColumn(#"Merged Queries", "Car Images", {"Image"}, {"Image"})
				in
				    #"Expanded Car Images"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

